version: '3'

services:
  mysqlauth:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "oauth"
    ports:
      - "3306:3306"
    networks:
      - oauth

  mysqlorderservice:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "delivery-order"
    ports:
      - "3305:3306"
    networks:
      - services

networks:
  oauth:
  services: